name: Deploy Storybook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Display Access Token
        run: echo "The access token in ${{secrets.GIT_ACCESS_TOKEN}}"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config user.email "shir.l@incentives-solutions.com"
          git config user.name "shirJoopy"
          git remote set-url origin git@github.com:shirJoopy/components-library.git

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build Storybook
        run: npm run deploy-storybook # Or the command to build Storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          publish_dir: ./docs # Update with your Storybook build directory
